#Importing and Linking all the HDL source files used in the design
import_files -library work -hdl_source script_support/hdl/wb_math_sub_multi.v
import_files -library work -hdl_source script_support/hdl/WB_Core.v
import_files -library work -hdl_source script_support/hdl/WB_Native.v
import_files -library work -hdl_source script_support/hdl/intensity_average.vhd
import_files -library work -hdl_source script_support/hdl/vb_sync2ff.sv
import_files -library work -hdl_source script_support/hdl/intensity_sum_pclk.sv
import_files -library work -hdl_source script_support/hdl/pulse_extend.sv
import_files -library work -hdl_source script_support/hdl/DDR_Frame_Blanker.v
import_files -library work -hdl_source script_support/hdl/alpha_blend.vhd
import_files -library work -hdl_source script_support/hdl/apb_wrapper.vhd
import_files -library work -hdl_source script_support/hdl/ddr_dma_pkg.vhd
import_files -library work -hdl_source script_support/hdl/ddr_dma_oimm_mux.vhd
import_files -library work -hdl_source script_support/hdl/ddr_dma_oimm_register.vhd
import_files -library work -hdl_source script_support/hdl/ddr_dma_oimm_throttler.vhd
import_files -library work -hdl_source script_support/hdl/ddr_dma_to_axi.vhd
import_files -library work -hdl_source script_support/hdl/ddr_dma_cdc.vhd
import_files -library work -hdl_source script_support/hdl/ddr_dma_fifo.vhd
import_files -library work -hdl_source script_support/hdl/ddr_dma_skid_buffer.vhd
import_files -library work -hdl_source script_support/hdl/ddr_dma_write.vhd
import_files -library work -hdl_source script_support/hdl/ddr_dma_write_axi4.vhd
import_files -library work -hdl_source script_support/hdl/ddr_dma_write_bif.vhd
import_files -library work -hdl_source script_support/hdl/video_switch.vhd
import_files -library work -hdl_source script_support/hdl/vbx_cm_cdc.vhd
import_files -library work -hdl_source script_support/hdl/frame_controller_disp.sv
import_files -library work -hdl_source script_support/hdl/frame_controller_vid_in.sv
import_files -library work -hdl_source script_support/hdl/frame_controller.sv
import_files -library work -hdl_source script_support/hdl/synchronizer_circuit.vhd
import_files -library work -hdl_source script_support/hdl/vbx_cm_async_fifo.vhd
import_files -library work -hdl_source script_support/hdl/video_cdc_fifo.vhd
import_files -library work -hdl_source script_support/hdl/scale.v
import_files -library work -hdl_source script_support/hdl/warp.v
import_files -library work -hdl_source script_support/hdl/draw_assist_pkg.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist_burst_aligner.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist_register.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist_fifo_sync.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist_registers.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist_throttler.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist_upsizer.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist_write_burst_buffer.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist.vhd
import_files -library work -hdl_source script_support/hdl/axi_arbiter.vhd
import_files -library work -hdl_source script_support/hdl/pulse_generator.vhd
